---
configSpecVersion: "2.0"
id: "de.gematik.erp-servicerequest"
author: "gematik GmbH"
description: "Referenzvalidator-Plugin für die Spezifikation 'KIM-Nachrichten für das E-Rezept'\
  \ FHIR-IG: https://gemspec.gematik.de/ig/fhir/erp-servicerequest/1.2.0/"
specUrl: "https://simplifier.net/packages/de.gematik.erp-servicerequest/1.2.0"
version: "1.2.0"
validation:
  dependencyLists:
  - fhirPackage: "de.gematik.erp-servicerequest#1.2.0"
  
